questions:
  - prompt: Qual a Empresa contratada para trabalhar no descomissionamento no campo {campo}?
    var: empresa
    type: string

  - prompt: Existe a presença de dutos flexíveis no campo {campo}?
    var: duto_flex
    type: boolean

  - prompt: Existe a presença de dutos rígidos no campo {campo}?
    var: duto_rig
    type: boolean

  - prompt: Existe a presença de Skids no campo {campo}?
    var: skid
    type: boolean

  - prompt: Existe a presença de Manifold no campo {campo}?
    var: manifold
    type: boolean

  - prompt: Existe a presença de cabos elétricos no campo {campo}?
    var: cabo_elet
    type: boolean

  - prompt: Qual a Distância da costa do campo {campo}? 
    var: distancia
    type: number

  - prompt: Qual a profundidade de Lâmina d'água do campo {campo}?
    var: lamina
    type: number

  - prompt: Qual a quantidade de Skids no campo {campo}?
    var: qtd_skid
    type: number

  - prompt: Qual a quantidade de Manifolds no campo {campo}?
    var: qtd_manifold
    type: number


    # Equipamento (booleano)
    # Está íntegro? (booleano)
prompt-suffix-boolean: >
  Em caso de resposta verdadeira, o valor deverá ser 1; Em qualquer outro caso, o valor deverá ser 0.
  Responda em json seguindo o formato: 
  {
      valor: number,
      fonte: string
  }

prompt-suffix-number: >
  Responda em json seguindo o formato: 
  {
      valor: number,
      fonte: string
  }

prompt-suffix-string: >
  Responda em json seguindo o formato: 
  {
      valor: string,
      fonte: string
  }
  

system-prompt: >
  Você é um assistente que deverá responder perguntas baseadas no contexto.
  Caso não saiba a resposta, admita não sabê-la. Leve em consideração que equipamentos presentes em plataformas em um determinado campo são
  contabilizados como pertencentes a este campo. Inclua o local de onde foi retirada a informação na resposta.

txt-docs-dir: "../plain-pages"
max-rag-ctx: 60000
# vec-store-path: "vec-stores/oai_3_large_vec_store.db"
vec-store-table: "oai_3_large_vec_store"
# vec-store-path: "vec-stores-bkp/oai_3_large_vec_store_marlin.db"
# vec-store-bkp-path: "vec-stores-bkp"

# documents:
#   - pdis-conceituais-marlim-voador  # Marlin
